language: java
jdk:
  - openjdk8

image: maven:3.3.9-jdk-8

build:
  script: "mvn install -B"

script:
 - mvn clean package
 - mvn cobertura:cobertura
 
after_success:
  - bash <(curl -s https://codecov.io/bash)